version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/www/shujaaz-comic
permissions:
  - object: /home/ubuntu/www/shujaaz-comic
    pattern: "**"
    owner:ubuntu
    group:ubuntu
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 6000
      runas: root
  AfterInstall:
    - location: scripts/install_os_dependencies.sh
      timeout: 6000
      runas: root
    - location: scripts/install_python_dependencies.sh
      timeout: 6000
      runas: root
    - location: scripts/migrate.sh
      timeout: 6000
      runas: root
    - location: scripts/apache.sh
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 600
      runas: root
      