version: 0.0
os: linux
files:
  - source: /shujaaz-comic/wsgi.py
    destination: /var/www/shujaaz-comic
  - source: /
    destination: /home/ec2-user/shujaaz-comic
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 600
      runas: root
      