version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov --cov-report=
            codecov --token=CODECOV_TOKEN
            coverage report
            coverage xml
      - run:
          name: Send coverage to CodeCov
          command: bash <(curl -s https://codecov.io/bash) -t "e5f89367-ca48-4787-9079-2239f1469c0b"

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  main:
    jobs:
      - build-and-test
      